# Generated by Django 5.0.3 on 2024-11-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="is_finished",
            field=models.BooleanField(db_default=False),
        ),
    ]
