# Generated by Django 5.0.3 on 2024-11-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0002_tournament_is_finished"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="winner",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
