# Generated by Django 5.0.3 on 2024-11-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0003_tournament_winner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="winner",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
